stages:
- test

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

eslint:
  stage: test
  image: node
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install 
    - pnpm run lint
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
